#!/bin/bash
SCRIPTDIR="$(dirname "$(realpath "$0")")"
source $SCRIPTDIR/setup_env.cfg

cmake -B $BUILDDIRACTS -S $SOURCEDIRACTS \
    -DACTS_BUILD_EXAMPLES=ON \
    -DACTS_BUILD_EXAMPLES_BINARIES=ON \
    -DACTS_BUILD_UNITTESTS=OFF \
    -DACTS_BUILD_INTEGRATIONTESTS=ON \
    -DACTS_BUILD_BENCHMARKS=ON \
    -DACTS_BUILD_FATRAS=ON \
    -DACTS_BUILD_DOCS=OFF \
    -DACTS_BUILD_EXAMPLES_PYTHIA8=ON \
    -DACTS_BUILD_EXAMPLES_HEPMC3=ON \
    -DACTS_BUILD_PLUGIN_EXATRKX=ON \
    -DACTS_BUILD_EXAMPLES_EXATRKX=ON \
    -DACTS_BUILD_PLUGIN_DD4HEP=ON \
    -DACTS_BUILD_EXAMPLES_DD4HEP=ON \
    -DACTS_BUILD_EXAMPLES_PYTHON_BINDINGS=ON \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_BUILD_TYPE=Release \
    -DACTS_BUILD_ODD=ON \
    -DCMAKE_INSTALL_PREFIX=$INSTALLDIR

cmake --build $BUILDDIRACTS --target install -- -j20
